trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'


stages: 
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    steps: 

    - task: Docker@2
      displayName: 'Docker build & Create Docker Image'
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'darshanadinushal/openshift-azuredevops'
        command: 'build'
        Dockerfile: 'openshiftapplication/Dockerfile'
        buildContext: '.'
        tags: '$(tag)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Test'
      inputs:
        command: test
        projects: 'openshiftapplicationtest/openshiftapplicationtest.csproj'
        publishTestResults: true
        arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'    
      
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

    - task: Docker@2
      displayName: 'Docker Push Image'
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'darshanadinushal/openshift-azuredevops'
        command: 'push'
        tags: '$(tag)'
