trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'


stages: 
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    steps: 

    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'darshanadinushal/openshift-azuredevops'
        command: 'build'
        Dockerfile: 'openshiftapplication/Dockerfile'
        buildContext: '.'
        tags: '$(tag)'

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: 'openshiftapplicationtest/**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'    

    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'darshanadinushal/openshift-azuredevops'
        command: 'push'
        tags: '$(tag)'
